apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-web
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`jellyfin.mvgates.com`)
      kind: Rule
      services:
        - name: jellyfin-service
          port: 80
  tls:
    secretName: jellyfin-tls
