apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yordan-marinov/homelab.git
    targetRevision: HEAD
    path: apps/management/homepage
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
