apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-ceph-conf
  namespace: rook-ceph
data:
  ceph.conf: |
    [global]
    fsid = 7803957b-7a69-49aa-97d9-90c03642648f
    mon_host = 10.104.58.227,10.96.205.248,10.96.54.135
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
    osd_journal_size = 5120

