apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      serviceAccountName: rook-ceph-system
      containers:
        - name: rook-ceph-tools
          image: docker.io/rook/ceph:v1.15.5
          command: ["/tini"]
          args: ["--", "/usr/local/bin/toolbox.sh"]
          env:
            - name: ROOK_CEPH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          tty: true
          stdin: true
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-client-admin
              mountPath: /etc/ceph/keyring
              subPath: keyring
      volumes:
        - name: ceph-conf
          configMap:
            name: rook-ceph-mon-endpoints
            items:
              - key: ceph.conf
                path: ceph.conf
        - name: ceph-client-admin
          secret:
            secretName: rook-ceph-admin-keyring

