apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      serviceAccountName: rook-ceph-tools
      containers:
        - name: rook-ceph-tools
          image: ceph/ceph:v19.2.0
          command: ["/bin/bash", "-c", "--"]
          args: ["sleep infinity"]
          tty: true
          stdin: true
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-client-admin
              mountPath: /etc/ceph/keyring
              subPath: keyring
      volumes:
        - name: ceph-conf
          configMap:
            name: rook-ceph-ceph-conf
        - name: ceph-client-admin
          secret:
            secretName: rook-ceph-admin-keyring

