apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      serviceAccountName: rook-ceph-tools
      containers:
        - name: rook-ceph-tools
          image: docker.io/rook/ceph:v1.15.5
          imagePullPolicy: IfNotPresent
          command: ["/tini"]
          args: ["--", "/usr/local/bin/toolbox.sh"]
          securityContext:
            privileged: true
          env:
            - name: ROOK_CEPH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          tty: true
          stdin: true
          volumeMounts:
            - name: ceph-config
              mountPath: /etc/ceph
            - name: ceph-mon-endpoint
              mountPath: /etc/rook
      volumes:
        - name: ceph-config
          emptyDir: {}
        - name: ceph-mon-endpoint
          configMap:
            name: rook-ceph-mon-endpoints

