apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  routes:
    - match: Host(`argocd.home.lab`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: argocd-headers
          namespace: argocd
      services:
        - name: argocd-server
          port: 80

