apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: infisical-server
  namespace: infisical
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`secrets.mvgates.com`)
      kind: Rule
      services:
        - name: infisical-app-infisical-standalone-infisical
          port: 8080
  tls:
    secretName: secrets-mvgates-tls
