apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph-dashboard
  namespace: rook-ceph
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ceph.home.lab`)
      kind: Rule
      middlewares:
        - name: ceph-dashboard-headers
      services:
        - name: rook-ceph-mgr-dashboard
          port: 7000
  tls:
    secretName: ceph-dashboard-tls
