spec:
  routes:
    - match: Host(`ceph.home.lab`)
      kind: Rule
      services:
        - name: rook-ceph-mgr-dashboard
          port: 8443
      middlewares:
        - name: ceph-dashboard-https-redirect

