apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ceph-dashboard-headers
  namespace: rook-ceph
spec:
  headers:
    # Forward proto so Ceph dashboard doesnâ€™t get confused with redirects
    customRequestHeaders:
      X-Forwarded-Proto: http

