apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: ceph-transport
  namespace: rook-ceph
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ceph-dashboard-headers
  namespace: rook-ceph
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph-dashboard-final
  namespace: rook-ceph
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ceph.home.lab`)
      kind: Rule
      middlewares:
        - name: ceph-dashboard-headers
      services:
        - name: rook-ceph-mgr-dashboard
          port: 8443
          scheme: https
          serversTransport: ceph-transport
  tls:
    secretName: ceph-dashboard-tls-selfsigned
