apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph-dashboard
  namespace: rook-ceph
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ceph.mvgates.com`)
      kind: Rule
      services:
        - name: rook-ceph-mgr-dashboard
          port: 8080
  tls:
    secretName: ceph-dashboard-tls
