apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ceph-dashboard-headers
  namespace: rook-ceph
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "ceph.home.lab"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph-dashboard-final
  namespace: rook-ceph
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ceph.home.lab`)
      kind: Rule
      middlewares:
        - name: ceph-dashboard-headers
      services:
        - name: rook-ceph-mgr-dashboard
          port: 7000
  tls:
    secretName: ceph-dashboard-tls-selfsigned
