apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph-dashboard
  namespace: rook-ceph
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ceph.home.lab`)
      kind: Rule
      services:
        - name: rook-ceph-mgr-dashboard
          port: 80

