apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-web
  namespace: vaultwarden
spec:
  entryPoints: [web]
  routes:
    - match: Host(`vault.home.lab`)
      kind: Rule
      services:
        - name: vaultwarden-service
          port: 80
